name: Run tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  run-tests:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: 5.5
            symfony-security: '^2.7'
          - php: 5.6
            symfony-security: '^3.0'
          - php: 7.0
            symfony-security: '^3.0'
          - php: 7.1
            symfony-security: '^3.0'
          - php: 7.2
            symfony-security: '^3.0'
          - php: 7.3
            symfony-security: '^3.0'
          - php: 7.4
            symfony-security: '^3.0'

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER__GITHUB_OAUTH_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require symfony/security:${{ matrix.symfony-security }} --no-update --no-install
          composer install --no-interaction --no-progress --no-ansi

      - name: Run PHPUnit test suite
        run: vendor/bin/phpunit

      - name: Run PHPSpec test suite
        run: vendor/bin/phpspec run
