name: Run tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  run-tests:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 5.5, 5.6, 7.0 ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.COMPOSER__GITHUB_OAUTH_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-ansi

      - name: Run PHPUnit test suite
        run: vendor/bin/phpunit

      - name: Run PHPSpec test suite
        run: vendor/bin/phpspec run
